base_config: ./base.yaml
experiment:
  name: espcn_apot

# training:
#   epochs: 32
quantization:
  method: apot
  bits: 8
  activation_bits: 8
  per_channel: true
  apot_m: 2
  apot_k: 4
  use_weight_norm: true
