base_config: base.yaml
experiment:
  run_name: sasrec_adaround

quantization:
  method: adaround
  bits: 8
  per_channel: true
  symmetric: true
  rounding_iters: 2000
  rounding_reg: 0.001
  base_checkpoint: ./checkpoints/sasrec_runs/sasrec_fp32.pth
  